### ISSUE TITLE
Where to ask questions?

### ISSUE THREAD

**Issue by ctr** [GPflow/GeometricKernels#130]
Hi

Where is the preferred place to discuss geometrickernels and ask questions? Could this be mentioned in your README? e.g. as issues here, or on slack, or a mailing list, or ...?

Thanks

Chris.

**Comment by vabor112** [comment]
Hey Chris,

You can post questions in issues using the `"How do I do ..." and other issues` template and the "question" label.

This [link](https://github.com/GPflow/GeometricKernels/issues/new?assignees=&labels=question&projects=&template=other-issue.md) chooses the right template and label for you.

PR #131 will add this to README under "If you have a question" section header.
