### ISSUE TITLE
Error arising for Jax arrays

### ISSUE THREAD

**Issue by thomaspinder** [GPflow/GeometricKernels#56]
I'm trying to get GeometricKernels to work in Jax. Adapting the example from your README as follows
```python
import gpjax as gpx 
import jax
import jax.numpy as jnp
from geometric_kernels.spaces.hypersphere import Hypersphere
from geometric_kernels.kernels.geometric_kernels import MaternKarhunenLoeveKernel

hypersphere = Hypersphere(dim=2)
xs = jnp.array([[0., 0., 1.], [0., 1., 0.], [1., 0., 0.]])
kernel = MaternKarhunenLoeveKernel(hypersphere, 100)

params, state = kernel.init_params_and_state()
print(kernel.K(params, state, xs))
```

raises the following error

```python
NotFoundLookupError: For function "from_numpy", signature Signature(builtins.float, numpy.ndarray) could not be resolved.
```

I'm running Jax v0.3.14 with Python 3.7.13 on a CPU Colab instance. 

Do you know how this can be resolved? I've little experience with lab, so apologise in advance if I've missed something fundamental!

**Comment by stoprightthere** [comment]
Hey @thomaspinder, thanks for submitting the issue!
To work with a non-`numpy` backend, you have to import specific backend e.g.
```python
import geometric_kernels.jax
```
We will adjust the code example to better reflect this.

**Comment by vdutor** [comment]
Hi Thomas, thank you for trying out geometric kernels. 

I was able to run the following snippet on my machine:
```python
import jax
import jax.numpy as jnp
import geometric_kernels.jax  # <---------  (1)
from geometric_kernels.spaces.hypersphere import Hypersphere
from geometric_kernels.kernels.geometric_kernels import MaternKarhunenLoeveKernel

hypersphere = Hypersphere(dim=2)
xs = jnp.array([[0., 0., 1.], [0., 1., 0.], [1., 0., 0.]])
kernel = MaternKarhunenLoeveKernel(hypersphere, 100)

params, state = kernel.init_params_and_state()
params["nu"] = jnp.array([5/2]).   # <---------  (2)
params["lengthscale"] = jnp.array([1.])
print(kernel.K(params, state, xs))
```
(1) Lets `geometric_kernels` know that you are using jax as a backend. This will initialise `lab` correctly and register the additional multiple dispatch functions we have defined.
(2) Converts the parameters of the kernel into a jax array. I think this is something that `geometric_kernels` should do for the users actually. Pinging @stoprightthere to hear what his thoughts are on this.

PS: With the release of your library `GPJax`, I think we should support it out-of-the-box for jax users in geometric_kernels. Similarly to how we have chosen GPflow for TensorFlow and GPyTorch for PyTorch. I'd be interested in hearing your opinion on this.

**Comment by stoprightthere** [comment]
> (2) Converts the parameters of the kernel into a jax array. I think this is something that `geometric_kernels` should do for the users actually. Pinging @stoprightthere to hear what his thoughts are on this.

Thanks for pointing this out! If we add support for `GPJax` — which I agree we should — then we can do this in a wrapper, like we do for tensorflow/gpflow and torch/gpytorch.

**Comment by thomaspinder** [comment]
Thanks @stoprightthere and @vdutor - my issue is resolved now.

On GPJax, I'd like to support GeometricKernels - this was actually my reason for starting to play with GeometricKernels last night! I think it should be relatively straightforward to achieve.
