### ISSUE TITLE
SO(n)

### ISSUE THREAD

**Issue by vabor112** [GPflow/GeometricKernels#62]
Port heat and Matérn kernels for SO(n) from https://github.com/imbirik/LieStationaryKernels

**Comment by stoprightthere** [comment]
What's the difference with PR #19 ?

**Comment by vabor112** [comment]
We should compare (hopefully Iskander can do that) how the existing PR is different from the version from https://github.com/imbirik/LieStationaryKernels and update it if there are things we now know how to implement better

**Comment by stoprightthere** [comment]
Done in PR #83
