### ISSUE TITLE
Integrate with GPJax

### ISSUE THREAD

**Issue by thomaspinder** [GPflow/GeometricKernels#74]
# Feature request

Geometric kernels can be easily supported by GPJax. There is an open PR to GPJax that demonstrates this:

https://github.com/JaxGaussianProcesses/GPJax/pull/159

## Motivation

Geometric kernels currently have a TensorFlow and GPyTorch backend. Supporting GPJax would add JAX to this list.

## Proposal

**Describe the solution you would like** I'd suggest lifting the `GeometricComputation` and `GeometricKernel` out of GPJax into Geometric kernels.

**Are you willing to open a pull request?** Yes

**Comment by stoprightthere** [comment]
@thomaspinder This would be awesome! Feel free to open a PR
