### ISSUE TITLE
How to represent the space for the circle

### ISSUE THREAD

**Issue by Fangwq** [GPflow/GeometricKernels#75]
I am confused about the space for the `circle`. In the file `circle.py`, the notes, in the function `_addition_theorem`, say that
the input param `X` and `X2` are one-dimensional. However, we should represent the circle with two parameters. So, the input should be two-dimensional.
How to understand this case? Or, we just denote the space for the circle with the following codes:
```
ProductDiscreteSpectrumSpace(Circle(), Circle(), num_eigen=num)
```
Check this code `https://github.com/Fangwq/Research-Progress/blob/main/20221201/circle_kernel.py`. Are these codes right or not? Thank you very much !

**Comment by vabor112** [comment]
Hello @Fangwq. The elements of `Circle` are supposed to be parameterized by their angle. `X` should consist of angles `X[i]` from $0$ to $2 \pi$ that correspond to the $(\cos(X[i]), \sin(X[i]))$ point on the circle $\\{ \mathbf{v} \in \mathbb{R}^2 : \|\mathbf{v}\| = 1 \\}$.

**Comment by vabor112** [comment]
Please tell me if this helps.

**Comment by Fangwq** [comment]
Thank you for your clarification. It works. The codes I have written are wrong.
