### ISSUE TITLE
question about the fucntion `per_level_to_separate`

### ISSUE THREAD

**Issue by Fangwq** [GPflow/GeometricKernels#76]
I run the demo code  `torus.py`. And I am a little confused about the function `per_level_to_separate`.
```
def per_level_to_separate(eigenindices, nums_per_level):

    separate = [num_per_level_to_mapping(npl) for npl in nums_per_level]

    total_eigenindices = []
    for index in eigenindices:
        separates = [separate[s][level] for s, level in enumerate(index)]
        # S lists, each with separate indices
        new_indices = list(itertools.product(*separates))
        total_eigenindices += new_indices

    out = from_numpy(eigenindices, np.array(total_eigenindices))
    return out
```
I print the result and find that the eigenvalue `index [0,1]` is corresponding to the eigenfunction `index [(0, 1), (0, 2)]`. 
Why this relationship is right? Any references I should catch up? Thank you very much.

**Comment by stoprightthere** [comment]
Hey @Fangwq, thanks for your continuing interest in our lib!

First, suppose we have a product space $\mathcal{S} = \mathcal{S}_1 \times \ldots \mathcal{S}_S$.
Eigenvalues on the product space are sums of the factors' eigenvalues:
```math
 \lambda_{l_1, \ldots, l_S} = \lambda^{1}_{l_1} + \ldots + \lambda^{S}_{l_S}
```
Each factor's eigenvalue corresponds to the factor's eigenfunctions (perhaps multiple eigenfunctions):
```math
 \lambda^{s}_{l_s} \leftrightarrow (\phi^{s}_{l_s, 1}, \ldots, \phi^{s}_{l_s, J_{l_s}})
```
We refer to this correspondence as a `level`.

Product-space eigenfunctions are products of factors' eigenfunctions within each level. Writing it out in latex would be too cumbersome, but essentialy you take all eigenfunctions corresponding to all your factors' eigenvalues and multiply them (factor-wise).

So, the code in `per_level_to_separate` is to compute indices of the factors' eigenfunctions for each product-space eigenfunction!

Let's break what is going on in the code.  First, `eigenindices` is an array of shape `[L, S]` where `S` is the number of factors and `L` is the number of levels. For each level of the product space, it stores indices of the eigenvalues of the factors. So,  `l`-th eigenvalue of the product space would be the sum of the `S` factors' eigenvalues whose indices are given by the `eigenindices[l]`. 

Now, an eigenvalue can correspond to multiple eigefunctions. `nums_per_level` is a list of `S` lists. Each list gives a mapping between an eigenvalue index and the number of the corresponding eigenfunctions.

The eigenfunctions of the product space are given by the product of the factors' eigenfunctions within each level.
So our goal is to compute, the indices of the factors' eigenfunctions, for each product-space eigenfunction.

We compute `separate` that gives `S` lists. Each sublist is of length `L`. Each sub-sublist gives factors' eigenfunction indices. So, `separate[s][l]` stores the indices of the eigenfunctions that correspond to `l`'th eigenvalue of `s`'th factor. 

 Now, we iterate over `eigenindices`. Remember, each `index` is a list of `S` elements that maps: for the factor `s` the eigenvalue index `index[s]`.
We compute `separates` by taking, for each factor `s`, `separate[s][index[s]]` eigenfunctions. So, `separates[s]` stores eigenfunctions indices for `s`th factor. Now just take all combinations of these indices by `itertools.product`. 
And repeat this for each `index`.

Hopefully this makes sense!

**Comment by Fangwq** [comment]
Thank you very much for your clarification. It seems that I should find some references to know more about the degenerate eigenfunctions of the Laplace–Beltrami operator defined on a circle. Any recommended references for the Laplace–Beltrami operators defined on Riemannian manifolds?

**Comment by vabor112** [comment]
You can check out this, for example: https://www.math.mcgill.ca/toth/spectral%20geometry.pdf
