### ISSUE TITLE
Bug in Gaussian process on mesh using GPflow

### ISSUE THREAD

**Issue by BinglinW** [GPflow/GeometricKernels#93]
There is a wrong when running the demo: Gaussian process on mesh using GPflow

base_kernel = MaternKarhunenLoeveKernel(mesh, nu, truncation_level)

TypeError: __init__() takes 3 positional arguments but 4 were given

**Comment by stoprightthere** [comment]
Hi @BinglinW , thank you for opening the issue!

The cause of the error is that `MaternKarhunenLoeveKernel` does not take `nu` as an argument now (it did in the early version, and we forgot to update the demo accordingly). The following should work:
```base_kernel = MaternKarhunenLoeveKernel(mesh, truncation_level)```

We will update the demo soon to reflect the change.

Thanks!
